// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplicationOdontoPrev.Data;

#nullable disable

namespace WebApplicationOdontoPrev.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241006174738_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.AnaliseRaioX", b =>
                {
                    b.Property<int>("IdAnaliseRaioX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_analise_raio_x");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnaliseRaioX"));

                    b.Property<string>("DsAnaliseRaioX")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("id_paciente");

                    b.Property<DateTime>("DtAnaliseRaioX")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ds_analise_raio_x");

                    b.Property<int>("IdRaioX")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("RaioXIdRaioX")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdAnaliseRaioX");

                    b.HasIndex("RaioXIdRaioX");

                    b.ToTable("T_ODTP_ANALISE_RAIO_X");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Dentista", b =>
                {
                    b.Property<int>("IdDentista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_dentista");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDentista"));

                    b.Property<string>("DsCro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("ds_cro");

                    b.Property<string>("DsDocIdentificacao")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("ds_doc_identificacao");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("NVARCHAR2(70)")
                        .HasColumnName("ds_email");

                    b.Property<string>("NmDentista")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_dentista");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nr_telefone");

                    b.HasKey("IdDentista");

                    b.ToTable("T_ODTP_DENTISTA");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.ExtratoPontos", b =>
                {
                    b.Property<int>("IdExtratoPontos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_extrato_pontos");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExtratoPontos"));

                    b.Property<string>("DsMovimentacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ds_movimentacao");

                    b.Property<DateTime>("DtExtrato")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_extrato");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("NrNumeroPontos")
                        .HasMaxLength(10)
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nr_numero_pontos");

                    b.HasKey("IdExtratoPontos");

                    b.HasIndex("IdPaciente");

                    b.ToTable("T_ODTP_EXTRATO_PONTOS");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_paciente");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("NVARCHAR2(70)")
                        .HasColumnName("ds_email");

                    b.Property<string>("DsSexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ds_sexo");

                    b.Property<string>("DtNascimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("dt_nascimento");

                    b.Property<int>("IdPlano")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmPaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nm_paciente");

                    b.Property<string>("NrCpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("nr_cpf");

                    b.Property<string>("NrTelefone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nr_telefone");

                    b.HasKey("IdPaciente");

                    b.HasIndex("IdPlano");

                    b.ToTable("T_ODTP_PACIENTE");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Perguntas", b =>
                {
                    b.Property<int>("IdPergunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_pergunta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPergunta"));

                    b.Property<string>("DsPergunta")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("NVARCHAR2(300)")
                        .HasColumnName("ds_pergunta");

                    b.HasKey("IdPergunta");

                    b.ToTable("T_ODTP_PERGUNTAS");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Plano", b =>
                {
                    b.Property<int>("IdPlano")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_plano");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlano"));

                    b.Property<string>("DsCodigoPlano")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("ds_codigo_plano");

                    b.Property<string>("NmPlano")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("nm_plano");

                    b.HasKey("IdPlano");

                    b.ToTable("T_ODTP_PLANO");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.RaioX", b =>
                {
                    b.Property<int>("IdRaioX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_raio_x");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRaioX"));

                    b.Property<byte[]>("DsRaioX")
                        .IsRequired()
                        .HasColumnType("RAW(2000)")
                        .HasColumnName("ds_raio_x");

                    b.Property<DateTime>("DtDataRaioX")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_data_raio_x");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRaioX");

                    b.HasIndex("IdPaciente");

                    b.ToTable("T_ODTP_RAIO_X");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Respostas", b =>
                {
                    b.Property<int>("IdResposta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_resposta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResposta"));

                    b.Property<string>("DsResposta")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("NVARCHAR2(400)")
                        .HasColumnName("ds_resposta");

                    b.Property<DateTime>("DtDataResposta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dt_data_resposta");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdPergunta")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdResposta");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdPergunta");

                    b.ToTable("T_ODTP_RESPOSTAS");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.AnaliseRaioX", b =>
                {
                    b.HasOne("WebApplicationOdontoPrev.Models.RaioX", "RaioX")
                        .WithMany()
                        .HasForeignKey("RaioXIdRaioX");

                    b.Navigation("RaioX");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.ExtratoPontos", b =>
                {
                    b.HasOne("WebApplicationOdontoPrev.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Paciente", b =>
                {
                    b.HasOne("WebApplicationOdontoPrev.Models.Plano", "Plano")
                        .WithMany()
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.RaioX", b =>
                {
                    b.HasOne("WebApplicationOdontoPrev.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WebApplicationOdontoPrev.Models.Respostas", b =>
                {
                    b.HasOne("WebApplicationOdontoPrev.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplicationOdontoPrev.Models.Perguntas", "Perguntas")
                        .WithMany()
                        .HasForeignKey("IdPergunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("Perguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
